server:
  port: 8080

spring:
  application:
    name: hot-reload     # matches the app label in Kubernetes
  profiles:
    active: kubernetes   # changed to kubernetes profile for full K8s deployment
  config:
    import: "kubernetes:"  # changed from optional to required for K8s
  cloud:
    kubernetes:
      config:
        enabled: true
      reload:
        enabled: true
        mode: event
        period: 30000

# Actuator endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,configprops
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    com.example: INFO
    org.springframework.cloud.kubernetes: DEBUG
    org.springframework.cloud.context: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.cloud.kubernetes.commons: DEBUG
    org.springframework.cloud.kubernetes.config: DEBUG
    org.springframework.cloud.kubernetes.reload: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"