apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-app
  labels:
    app: sample-app
data:
  # the key "message" matches @Value("${message}") in our code
  message: "Initial hello from ConfigMap!"
