---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reload-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-watcher
  namespace: default
rules:
  # Allow listing, watching, and getting ConfigMaps (and Secrets if you enable secrets)
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-watcher-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: reload-sa
    namespace: default
roleRef:
  kind: Role
  name: configmap-watcher
  apiGroup: rbac.authorization.k8s.io
