---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hot-reload-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hot-reload-role
rules:
  # Allow listing, watching, and getting ConfigMaps (and Secrets if you enable secrets)
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hot-reload-rb
subjects:
  - kind: ServiceAccount
    name: hot-reload-sa
roleRef:
  kind: Role
  name: hot-reload-role
  apiGroup: rbac.authorization.k8s.io
